# Generated by Django 2.2 on 2019-04-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arabictweets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchKeywords',
        ),
    ]
