# Generated by Django 2.2 on 2019-04-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabictweets', '0002_delete_searchkeywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittertext',
            name='tweet_datetime',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='tweet_datetime'),
        ),
    ]
