# Generated by Django 2.2 on 2019-04-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabictweets', '0003_auto_20190402_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittertext',
            name='tweet_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tweet_source'),
        ),
    ]
