# Generated by Django 2.2 on 2019-04-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arabictweets', '0005_auto_20190403_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twittertext',
            options={'verbose_name_plural': 'tweet_texts'},
        ),
    ]
